<a href="https://colab.research.google.com/github/proteus21/DATA-SCIENCE-STUDY/blob/main/Computer%20Vision/TensorFlow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow 2.0 <a class="tocSkip">

In [ ]:
import tensorflow as tf
print('Wersja TensorFlow :',tf.__version__)
import numpy as np
print('Wersja Numpy :',np.__version__)
import sys
print('Interpreter Pythona i wersja:',sys.version)

Wersja TensorFlow : 2.9.2
Wersja Numpy : 1.21.6
Interpreter Pythona i wersja: 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]


# Hello TensorFlow 

In [ ]:
hello = tf.constant('Witamy w projekcie TensorFlow!!')
tf.print(hello)
print(hello)

Witamy w projekcie TensorFlow!!
tf.Tensor(b'Witamy w projekcie TensorFlow!!', shape=(), dtype=string)


# Stałe

In [ ]:
const1 = tf.constant(34, name='x', dtype=tf.float32)
const2 = tf.constant((2,59.0), name='y', dtype=tf.float64)
const3 = tf.constant(32.0, name='z')
print('const1 (x): ', const1)
print('const2 (y): ', const2)
print('const3 (z): ', const3)

const1 (x):  tf.Tensor(34.0, shape=(), dtype=float32)
const2 (y):  tf.Tensor([ 2. 59.], shape=(2,), dtype=float64)
const3 (z):  tf.Tensor(32.0, shape=(), dtype=float32)


In [ ]:
print('run([const1,const2,const3]) : ', end='')
tf.print([const1, const2, const3])

run([const1,const2,const3]) : [34, 59, 32]


# Operacje

In [ ]:
op1 = tf.add(const1, const3)
op2 = tf.multiply(const1, const3)
print('op1 : ', op1)
print('op2 : ', op2)

op1 :  tf.Tensor(66.0, shape=(), dtype=float32)
op2 :  tf.Tensor(1088.0, shape=(), dtype=float32)


In [ ]:
print('run(op1) : ', end='')
tf.print(op1)
print('run(op2) : ', end='')
tf.print(op2)

run(op1) : 66
run(op2) : 1088


# Funkcje

In [ ]:
@tf.function
def add_func(x):
    y = x + 10
    return y

In [ ]:
x = tf.constant([10, 20, 30, 40])

In [ ]:
result = add_func(x)

In [ ]:
print(result)

Tensor("PartitionedCall:0", shape=(4,), dtype=int32)


In [ ]:
tf.print(result)

<tf.Operation 'PrintV2' type=PrintV2>

# Tworzenie tensorów z istniejących obiektów

## Tensory zerowego rzędu (skalary)

In [ ]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)

print('tf_t : ', tf_t)
print('run(tf_t) : ', end='')
tf.print(tf_t)

tf_t :  tf.Tensor(5.0, shape=(), dtype=float64)
run(tf_t) : 5


## Tensory 1. rzędu (wektory)

In [ ]:
a1dim = np.array([1, 2, 3, 4, 5.99])
print('Kształt a1dim : ', a1dim.shape)

tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0] : ', tf_t[0])
print('tf_t[0] : ', tf_t[2])
print('run(tf_t) : ')
tf.print(tf_t)

Kształt a1dim :  (5,)
tf_t :  tf.Tensor([1.   2.   3.   4.   5.99], shape=(5,), dtype=float64)
tf_t[0] :  tf.Tensor(1.0, shape=(), dtype=float64)
tf_t[0] :  tf.Tensor(3.0, shape=(), dtype=float64)
run(tf_t) : 
[1 2 3 4 5.99]


## Tensory 2. rzędu (macierze)

In [ ]:
a2dim = np.array([(1, 2, 3, 4, 5.99),
                  (2, 3, 4, 5, 6.99),
                  (3, 4, 5, 6, 7.99)
                  ])
print('Kształt a2dim : ', a2dim.shape)

tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0] : ', tf_t[0][0])
print('tf_t[1][2] : ', tf_t[1][2])
print('run(tf_t) :') 
tf.print(tf_t)

Kształt a2dim :  (3, 5)
tf_t :  tf.Tensor(
[[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]], shape=(3, 5), dtype=float64)
tf_t[0][0] :  tf.Tensor(1.0, shape=(), dtype=float64)
tf_t[1][2] :  tf.Tensor(4.0, shape=(), dtype=float64)
run(tf_t) :
[[1 2 3 4 5.99]
 [2 3 4 5 6.99]
 [3 4 5 6 7.99]]


## Tensory 3. rzędu

In [ ]:
a3dim = np.array([[[1, 2],
                   [3, 4]
                   ],
                  [[5, 6],
                   [7, 8]
                   ]
                  ])
print('Kształt a3dim : ', a3dim.shape)

tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0][0] : ', tf_t[0][0][0])
print('tf_t[1][1][1] : ', tf_t[1][1][1])
print('run(tf_t) : ')
tf.print(tf_t)

Kształt a3dim :  (2, 2, 2)
tf_t :  tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float64)
tf_t[0][0][0] :  tf.Tensor(1.0, shape=(), dtype=float64)
tf_t[1][1][1] :  tf.Tensor(8.0, shape=(), dtype=float64)
run(tf_t) : 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Zmienne

In [ ]:
# Placeholdery nie są wykonywalne natychmiast, więc musimy wyłączyć żądania wykonania w TF2
tf.compat.v1.disable_eager_execution()

# Model liniowy y = w * x + b
# Definiowanie parametrów modelu
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Definiowanie wejścia i wyjścia modelu
x = tf.compat.v1.placeholder(tf.float32)
y = w * x + b

print('w:', w)
print('x:', x)
print('b:', b)
print('y:', y)

w: <tf.Variable 'Variable_2:0' shape=(1,) dtype=float32>
x: Tensor("Placeholder_1:0", dtype=float32)
b: <tf.Variable 'Variable_3:0' shape=(1,) dtype=float32>
y: Tensor("add_1:0", dtype=float32)


In [ ]:
# Inicjacja sesji i wydruk zmiennej y
with tf.compat.v1.Session() as sess:
  sess.run(tf.compat.v1.global_variables_initializer())
  print('run(y,{x:[1,2,3,4]}) : ', sess.run(y, {x: [1, 2, 3, 4]}))

run(y,{x:[1,2,3,4]}) :  [0.         0.3        0.6        0.90000004]


# Tworzenie tensorów z funkcji bibliotecznych

In [ ]:
a = tf.zeros((100,50))

In [ ]:
b = tf.ones((100,))
print(b)

Tensor("ones_1:0", shape=(100,), dtype=float32)


In [ ]:
c = tf.fill((100,), 5)
print(c)

Tensor("Fill:0", shape=(100,), dtype=int32)


# Grafy obliczeniowe

## Budowa i uruchomienie prostego grafu obliczeniowego

In [ ]:
# Placeholdery nie są wykonywalne natychmiast, więc musimy wyłączyć żądania wykonania w TF2
tf.compat.v1.disable_eager_execution()

# Model liniowy y = w * x + b
# Definiowanie parametrów modelu
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Definiowanie wejścia i wyjścia modelu
x = tf.compat.v1.placeholder(tf.float32)
y = w * x + b
output = 0

with tf.compat.v1.Session() as sess:
    # Inicjacja i wydruk zmiennej y
    tf.compat.v1.global_variables_initializer().run()
    output = sess.run(y, {x: [1, 2, 3, 4]})
print('wyjście : ', output)

wyjście :  [0.         0.3        0.6        0.90000004]


## Graf na urządzeniach obliczeniowych

### Lista dostępnych urządzeń

In [ ]:
#na Collabie wcześniej zmień akcelerację sprzętową na GPU
from tensorflow.python.client import device_lib

print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 6259035098617011906
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 14415560704
locality {
  bus_id: 1
  links {
  }
}
incarnation: 11687619777407950705
physical_device_desc: "device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5"
xla_global_id: 416903419
]


### Domyślne rozmieszczenie

In [ ]:
from tensorflow.python.framework import ops
ops.reset_default_graph()

# Definiowanie parametrów modelu
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Definiowanie wejścia i wyjścia modelu
x = tf.compat.v1.placeholder(tf.float32)
y = w * x + b

config = tf.compat.v1.ConfigProto()
config.log_device_placement = True

with tf.compat.v1.Session(config=config) as sess:
    # inicjacja i wydruk zmiennej y
    sess.run(tf.compat.v1.global_variables_initializer())
    print('wyjście', sess.run(y, {x: [1, 2, 3, 4]}))

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5

wyjście [0.         0.3        0.6        0.90000004]


### Rozmieszczanie na CPU

In [ ]:
ops.reset_default_graph()

with tf.device('/device:CPU:0'):
    # Definiowanie parametrów modelu
    w = tf.Variable([.3], tf.float32)
    b = tf.Variable([-.3], tf.float32)
    # Definiowanie wejścia i wyjścia modelu
    x = tf.compat.v1.placeholder(tf.float32)
    y = w * x + b

    config = tf.compat.v1.ConfigProto()
    config.log_device_placement = True

    with tf.compat.v1.Session(config=config) as sess:
        # inicjacja i wydruk zmiennej y
        sess.run(tf.compat.v1.global_variables_initializer())
        print('wyjście', sess.run(y, {x: [1, 2, 3, 4]}))

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5

wyjście [0.         0.3        0.6        0.90000004]


### Rozmieszczanie na CPU i GPU

In [ ]:
ops.reset_default_graph()

with tf.device('/device:CPU:0'):
    # Definiowanie parametrów modelu
    w = tf.Variable([.3], tf.float32)
    b = tf.Variable([-.3], tf.float32)
    # Definiowanie wejścia i wyjścia modelu
    x = tf.compat.v1.placeholder(tf.float32)
with tf.device('/device:GPU:0'):
    y = w * x + b

config = tf.compat.v1.ConfigProto()
config.log_device_placement = True

with tf.compat.v1.Session(config=config) as sess:
    # inicjacja i wydruk zmiennej y
    sess.run(tf.compat.v1.global_variables_initializer())
    print('wyjście', sess.run(y, {x: [1, 2, 3, 4]}))

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5

wyjście [0.         0.3        0.6        0.90000004]


## Wykonywanie grafu g jako domyślnego

In [ ]:
g = tf.Graph()
output = 0

# Przyjmujemy model liniowy y = w * x + b

with g.as_default():
    # Definiowanie parametrów modelu
    w = tf.Variable([.3], tf.float32)
    b = tf.Variable([-.3], tf.float32)
    # Definiowanie wejścia i wyjścia modelu
    x = tf.compat.v1.placeholder(tf.float32)
    y = w * x + b

with tf.compat.v1.Session(graph=g) as sess:
    # Inicjacja i wydruk zmiennej y
    tf.compat.v1.global_variables_initializer().run()
    output = sess.run(y, {x: [1, 2, 3, 4]})

print('wyjście : ', output)

wyjście :  [0.         0.3        0.6        0.90000004]


# Regresja logistyczna z TensorFlow

### UWAGA! Konieczne ponowne uruchomienie środowiska ze względu na korzystanie z eager mode wyłączonym wcześniej!

## Przygotowanie danych

In [ ]:
import tensorflow as tf
from keras.datasets import mnist
import numpy as np

# Przygotuj dane x i y

(x_train,y_train), (x_test,y_test)=mnist.load_data()

print('Wczytane x i y')
print('Szkolenie: x:{}, y:{}'.format(len(x_train),y_train.shape))
print('Test: x:{}, y:{}'.format(x_test.shape,y_test.shape))
print(x_train[0])

11490434/11490434 [==============================] - 0s 0us/step
Wczytane x i y
Szkolenie: x:60000, y:(60000,)
Test: x:(10000, 28, 28), y:(10000,)
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 

In [ ]:
# Ładowanie danych
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Konwersja na float32
x_train, x_test = np.array(x_train, np.float32), np.array(x_test, np.float32)

# Spłaszczenie zdjęć do jednowymiarowego wektora o 784 pikselach (28x28).
x_train, x_test = x_train.reshape([-1, 784]), x_test.reshape([-1, 784])

# Normalizacja wartości z [0, 255] na [0, 1].
x_train, x_test = x_train / 255., x_test / 255.

## Dzielenie danych na batche

In [ ]:
# Parametry MNIST

num_classes = 10 # 0 to 9 digits

num_features = 784 # 28*28

# Parametry trenowania

learning_rate = 0.01

training_steps = 1000

batch_size = 256

display_step = 5

In [ ]:
train_data=tf.data.Dataset.from_tensor_slices((x_train,y_train))

train_data=train_data.repeat().shuffle(5000).batch(batch_size).prefetch(1)

## Budowanie modelu

In [ ]:
# Wagi o rozmiarze [784, 10]
W = tf.Variable(tf.ones([num_features, num_classes]), tf.float32, name="weight")

# Bias o rozmiarze [10]

b = tf.Variable(tf.zeros([num_classes]), tf.float32, name="bias")

## Funkcja straty i regresji logistycznej

In [ ]:
def cross_entropy(y_pred, y_true):
    # Enkodowanie etykiet
    y_true = tf.one_hot(y_true, depth=num_classes)
    
    # W celu uniknięcia wartości zerowych zamieniamy małe wartości na 1
    y_pred = tf.clip_by_value(y_pred, 1e-9, 1.)
    
    # Liczenie entropii 
    return tf.reduce_mean(-tf.reduce_sum(y_true * tf.math.log(y_pred),1))


def logistic_regression(x):

    # Zastosujemy softmax do normalizacji wyników do rozkładu prawdopodobieństwa.
    return tf.nn.softmax(tf.matmul(x, W) + b)

## Funkcja dokładności i optymalizator

In [ ]:
def accuracy(y_pred, y_true):

  # Klasa przewidywana to indeks najwyższego wyniku w wektorze predykcji (czyli argmax)

  correct_prediction = tf.equal(tf.argmax(y_pred, 1), tf.cast(y_true, tf.int64))

  return tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

# Optymalizator SGD

optimizer = tf.optimizers.SGD(learning_rate)

## Trenowanie modelu

In [ ]:
# Proces optymalizacji

def run_optimization(x, y):

    with tf.GradientTape() as g:
        
        pred = logistic_regression(x)
        
        loss = cross_entropy(pred, y)

    # Obliczanie gradientów

    gradients = g.gradient(loss, [W, b])

    # Aktualizacja wag i biasów

    optimizer.apply_gradients(zip(gradients, [W, b]))

In [ ]:
# Rozpoczęcie trenowania dla danej ilości epok

for step, (batch_x, batch_y) in enumerate(train_data.take(training_steps), 1):

    run_optimization(batch_x, batch_y)

    #Obliczanie parametrów dla każdej epoki

    if step % display_step == 0:

        pred = logistic_regression(batch_x)

        loss = cross_entropy(pred, batch_y)

        acc = accuracy(pred, batch_y)

        print("step: %i, loss: %f, accuracy: %f" % (step, loss, acc))

In [ ]:
print(W[280])

tf.Tensor(
[0.9999926  0.9999944  0.9999932  0.9999879  0.9999781  0.99998885
 0.99999154 1.0001172  0.99999005 0.99996656], shape=(10,), dtype=float32)


In [ ]:
# Testowanie modelu
pred = logistic_regression(x_test)

print("Test Accuracy: %f" % accuracy(pred, y_test))

Test Accuracy: 0.870500


# Regresja logistyczna z Keras

In [ ]:
(x_train,y_train), (x_test,y_test) = mnist.load_data()

mnist.y_onehot = True

x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='sgd',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=15)

model.evaluate(x_test, y_test)

Epoch 1/15
1875/1875 [==============================] - 13s 6ms/step - loss: 0.7790 - accuracy: 0.8163
Epoch 2/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4542 - accuracy: 0.8812
Epoch 3/15
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4021 - accuracy: 0.8919
Epoch 4/15
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3761 - accuracy: 0.8969
Epoch 5/15
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3595 - accuracy: 0.9011
Epoch 6/15
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3479 - accuracy: 0.9037
Epoch 7/15
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3389 - accuracy: 0.9058
Epoch 8/15
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3319 - accuracy: 0.9080
Epoch 9/15
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3261 - accuracy: 0.9093
Epoch 10/15
1875/1875 [==============================] - 3s 2ms/step - loss: 0.32

[0.2946564555168152, 0.9176999926567078]