<a href="https://colab.research.google.com/github/proteus21/DATA-SCIENCE-STUDY/blob/main/Machine%20Learning/02_regression/02_gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To install scikit-learn library use command below

Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:

**!pip install scikit-learn**

In order to update to newest scikit-learn library, use command below

Aby zaktualizować do najnowszej wersji bibliotekę scikit-learn, użyj polecenia poniżej:

**!pip install --upgrade scikit-learn**

### Contenst:
1. [Import library](#0)
2. [Generate data](#1)
3. [Prepare input data](#2)
4. [Random paratmetr initialization](#3)
5. [Simple gradient method](#4)
6. [Match visualistion](#5)


### Spis treści:
1. [Import bibliotek](#0)
2. [Wygenerowanie danych](#1)
3. [Przygotowanie danych](#2)
4. [Losowa inicjalizacja parametrów](#3)
5. [Metoda gradientu prostego](#4)
6. [Wizualizacja dopasowania](#5)


### <a name='0'></a> Import bibliotek  /Import library

In [2]:
import numpy as np
import pandas as pd
import plotly.express as px
np.random.seed(42)

### <a name='1'></a> Przygotowanie danych /Prepare input data

In [3]:
X1=np.array([1,2,3,4,5,6])
Y=np.array([3000,3250,3500,3750,4000,4250])
m=len(X1)


print(f'Lata pracy / Years of the work {X1}')
print(f'Wynagrodzenie / Solary {Y}')
print(f'Liczba próbek / Number of trials {m}')

Lata pracy / Years of the work [1 2 3 4 5 6]
Wynagrodzenie / Solary [3000 3250 3500 3750 4000 4250]
Liczba próbek / Number of trials 6


In [4]:
X1=X1.reshape(m,1) #
Y=Y.reshape(-1,1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [5]:
bias=np.ones((m,1)) # wyraz wolny / Matrix with value 1
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [6]:
X=np.append(bias,X1,axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


### <a name='4'></a> Losowa inicjalizacja parametrów / Random parameter initialization

In [8]:
eta=0.01 # wskaznik uczenia / learn factor
weights=np.random.randn(2,1) #Return a sample (or samples) from the “standard normal” distribution.
print(weights)
print(X)

[[0.64768854]
 [1.52302986]]
[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]


### <a name='5'></a>  Metoda gradientu prostego  / Simple gradient method

In [10]:
intercept=[]
coef=[]
for i in range(3000):
  gradient=(2/m)*X.T.dot(X.dot(weights)-Y)
  weights=weights-eta*gradient
  intercept.append(weights[0][0])
  coef.append(weights[1][0])
print(weights)

[[2749.95616558]
 [ 250.01023882]]


In [11]:
df=pd.DataFrame(data={'intercept':intercept,'coef':coef})
df.head()

intercept        coef
0  125.213127  450.867862
1  163.648115  573.673025
2  192.718041  656.536839
3  215.406101  712.230402
4  233.741851  749.442086

### <a name='6'></a>  Wizualizacja dopasowania  / Match visualistion

In [12]:
px.line(df,y='intercept', width=800, title='Dopsowanie Intercept')

In [13]:
px.line(df,y='coef', width=800, title='Dopasowanie:coef')